export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_FOCUS_DAY = 'UPDATE_FOCUS_DAY';
export const UPDATE_TRIP_DURATION = 'UPDATE_TRIP_DURATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';

